module.exports = {
	'env': {
		'amd': false,
		'browser': true,
		'mocha': true,
		'node': true
	},

	'globals': {
		'alert': true,
		'AUI': true,
		'CKEDITOR': true,
		'confirm': true,
		'Liferay': true,
		'submitForm': true,
		'themeDisplay': true,
		'tinyMCE': true,
		'YUI': true
	},

	'rules': {
		'csf-liferay-provide-format': 2,
		'block-scoped-var': 2,
		'brace-style': [2, 'stroustrup'],
		'camelcase': 0,
		'comma-dangle': [2, 'never'],
		'comma-spacing': 2,
		'comma-style': [2, 'last'],
		'complexity': [0, 11],
		'consistent-return': 2,
		'consistent-this': [1, 'instance'],
		'csf-array-spacing': 2,
		'csf-array-spacing-chars': 2,
		'csf-catch-arg-name': 2,
		'csf-catch-format': 2,
		'csf-format-args': 2,
		'csf-format-constants': 2,
		'csf-format-multiline-vars': 2,
		'csf-multiple-vars': 2,
		'csf-no-extra-semi': 2,
		'csf-no-is-prefix': 2,
		'csf-no-unused-vars': 2,
		'csf-no-use-before-define': [2, {'samescope': true}],
		'csf-sort-constants': 2,
		'csf-sort-props': 2,
		'csf-sort-requires': 2,
		'csf-sort-vars': 2,
		'curly': [2, 'all'],
		'default-case': 0,
		'dot-location': [2, 'property'],
		'dot-notation': 2,
		'eol-last': 0,
		'eqeqeq': 0,
		'func-names': 0,
		'func-style': [0, 'declaration'],
		'generator-star-spacing': 0,
		'guard-for-in': 0,
		'handle-callback-err': 0,
		'indent': [2, 'tab'],
		'key-spacing': 2,
		'max-depth': [0, 4],
		'max-len': [0, 80, 4],
		'max-nested-callbacks': [0, 2],
		'max-params': [0, 3],
		'max-statements': [0, 10],
		'new-cap': 0,
		'new-parens': 2,
		'newline-after-var': 0,
		'no-alert': 0,
		'no-array-constructor': 2,
		'no-bitwise': 0,
		'no-caller': 2,
		'no-catch-shadow': 2,
		'no-cond-assign': 2,
		'no-console': 2,
		'no-constant-condition': 2,
		'no-control-regex': 2,
		'no-debugger': 2,
		'no-delete-var': 2,
		'no-div-regex': 0,
		'no-dupe-args': 2,
		'no-dupe-keys': 2,
		'no-duplicate-case': 2,
		'no-else-return': 2,
		'no-empty': 0,
		'no-empty-class': 2,
		'no-empty-label': 2,
		'no-eq-null': 0,
		'no-eval': 2,
		'no-ex-assign': 2,
		'no-extend-native': 2,
		'no-extra-bind': 2,
		'no-extra-boolean-cast': 2,
		'no-extra-parens': 0,
		'no-extra-semi': 0,
		'no-fallthrough': 2,
		'no-floating-decimal': 0,
		'no-func-assign': 2,
		'no-implied-eval': 2,
		'no-inline-comments': 2,
		'no-inner-declarations': [2, 'functions'],
		'no-invalid-regexp': 2,
		'no-irregular-whitespace': 2,
		'no-iterator': 2,
		'no-label-var': 2,
		'no-labels': 2,
		'no-lone-blocks': 2,
		'no-lonely-if': 2,
		'no-loop-func': 2,
		'no-mixed-requires': [0, false],
		'no-mixed-spaces-and-tabs': [0, false],
		'no-multi-spaces': 2,
		'no-multi-str': 2,
		'no-multiple-empty-lines': [2, {max: 2}],
		'no-native-reassign': 2,
		'no-negated-in-lhs': 2,
		'no-nested-ternary': 2,
		'no-new': 0,
		'no-new-func': 2,
		'no-new-object': 2,
		'no-new-require': 0,
		'no-new-wrappers': 2,
		'no-obj-calls': 2,
		'no-octal': 2,
		'no-octal-escape': 2,
		'no-param-reassign': 0,
		'no-path-concat': 0,
		'no-plusplus': 0,
		'no-process-env': 0,
		'no-process-exit': 2,
		'no-proto': 2,
		'no-redeclare': 2,
		'no-regex-spaces': 2,
		'no-reserved-keys': 0,
		'no-restricted-modules': 0,
		'no-return-assign': 2,
		'no-script-url': 0,
		'no-self-compare': 0,
		'no-sequences': 2,
		'no-shadow': 0,
		'no-shadow-restricted-names': 2,
		'no-spaced-func': 2,
		'no-sparse-arrays': 2,
		'no-sync': 0,
		'no-ternary': 0,
		'no-throw-literal': 0,
		'no-trailing-spaces': 2,
		'no-undef': 2,
		'no-undef-init': 2,
		'no-undefined': 0,
		'no-underscore-dangle': 0,
		'no-unreachable': 2,
		'no-unused-expressions': 2,
		'no-unused-vars': [2, {'vars': 'local', 'args': 'none'}],
		'no-use-before-define': 0,
		'no-var': 0,
		'no-void': 0,
		'no-warning-comments': [0, { 'terms': ['todo', 'fixme', 'xxx'], 'location': 'start' }],
		'no-with': 2,
		'no-wrap-func': 2,
		'one-var': 0,
		'operator-assignment': [2, 'always'],
		'padded-blocks': 0,
		'quote-props': 0,
		'quotes': [2, 'single'],
		'radix': 2,
		'semi': [2, 'always'],
		'semi-spacing': [2, {before: false, after: true}],
		'sort-vars': [2, {ignoreCase: true}],
		'space-after-keywords': [2, 'always'],
		'space-before-blocks': [2, 'always'],
		'space-before-function-paren': [2, 'never'],
		'space-in-brackets': [0, 'never'],
		'space-in-parens': [2, 'never'],
		'space-infix-ops': 2,
		'space-return-throw-case': 2,
		'space-unary-ops': [1, {'words': true, 'nonwords': false}],
		'spaced-line-comment': [2, 'always'],
		'strict': 0,
		'use-isnan': 2,
		'valid-jsdoc': 0,
		'valid-typeof': 2,
		'vars-on-top': 0,
		'wrap-iife': 0,
		'wrap-regex': 0,
		'yoda': 2
	}
};