module.exports = {

	// 'plugins': [
	// 	'react'
	// ],

	'globals': {

	},

	'rules': {
		'csf-at-rule-empty-line': ['always', {except: ['first-nested']}],
		// 'at-rule-empty-line-before': ['always', {except: ['first-nested']}],
		'at-rule-no-vendor-prefix': true,
		'block-closing-brace-newline-after': 'always',
		'block-closing-brace-newline-before': 'always',
		// 'block-closing-brace-space-after': 'never',
		// 'block-closing-brace-space-before': 'never',
		// 'block-no-empty': true,
		'block-no-single-line': true,
		'block-opening-brace-newline-after': 'always',
		// 'block-opening-brace-newline-before': 'always'|'always-single-line'|'never-single-line'|'always-multi-line'|'never-multi-line',
		// 'block-opening-brace-space-after': 'never',
		'block-opening-brace-space-before': 'always',
		'color-hex-case': 'upper',
		'color-hex-length': 'short',
		'color-named': 'never',
		// 'color-no-hex': true,
		'color-no-invalid-hex': true,
		'comment-empty-line-before': ['always', {except: ['first-nested']}],
		'comment-whitespace-inside': 'always',
		// 'custom-media-pattern': string,
		// 'custom-property-no-outside-root': true,
		// 'custom-property-pattern': string,
		'declaration-bang-space-after': 'never',
		'declaration-bang-space-before': 'always',
		'declaration-block-no-duplicate-properties': true,
		'declaration-block-no-shorthand-property-overrides': true,
		'declaration-block-properties-order': 'alphabetical',
		'declaration-block-semicolon-newline-after': 'always',
		'declaration-block-semicolon-newline-before': 'never',
		// 'declaration-block-semicolon-space-after': 'always'|'never'|'always-single-line'|'never-single-line',
		'declaration-block-semicolon-space-before': 'never',
		// 'declaration-block-single-line-max-declarations': int,
		'declaration-block-trailing-semicolon': 'always',
		// 'declaration-colon-newline-after': 'always'|'always-multi-line',
		'declaration-colon-space-after': 'always',
		'declaration-colon-space-before': 'never',
		// 'declaration-no-important': true,
		'font-family-name-quotes': 'single-where-recommended',
		'font-weight-notation': 'named-where-possible',
		// 'function-blacklist': 'rgba',
		'function-calc-no-unspaced-operator': true,
		'function-comma-newline-after': 'never',
		'function-comma-newline-before': 'never',
		'function-comma-space-after': 'always',
		'function-comma-space-before': 'never',
		// 'function-linear-gradient-no-nonstandard-direction': true,
		// 'function-parentheses-newline-inside': 'always'|'always-multi-line'|'never-multi-line',
		'function-parentheses-space-inside': 'never',
		'function-url-quotes': 'none',
		// 'function-whitelist': string|[],
		'function-whitespace-after': 'always',
		'indentation': 'tab',
		'max-empty-lines': 1,
		// 'max-line-length': int,
		// 'max-nesting-depth': int,
		'media-feature-colon-space-after': 'always',
		'media-feature-colon-space-before': 'never',
		// 'media-feature-name-no-vendor-prefix': true,
		'media-feature-no-missing-punctuation': true,
		'media-feature-range-operator-space-after': 'always',
		'media-feature-range-operator-space-before': 'always',
		// 'media-query-list-comma-newline-after': 'always'|'always-multi-line'|'never-multi-line',
		// 'media-query-list-comma-newline-before': 'always'|'always-multi-line'|'never-multi-line',
		// 'media-query-list-comma-space-after': 'always'|'never'|'always-single-line'|'never-single-line',
		// 'media-query-list-comma-space-before': 'always'|'never'|'always-single-line'|'never-single-line',
		'media-query-parentheses-space-inside': 'never',
		// 'no-browser-hacks': true,
		// 'no-descending-specificity': true, // Maybe
		// 'no-duplicate-selectors': true, // Maybe
		'no-eol-whitespace': true,
		// 'no-invalid-double-slash-comments': true,
		// 'no-missing-eof-newline': true,
		// 'no-unknown-animations': true,
		// 'no-unsupported-browser-features': true,
		'number-leading-zero': 'always',
		'number-max-precision': 3,
		'number-no-trailing-zeros': true,
		'number-zero-length-no-unit': true,
		// 'property-blacklist': string|[],
		'property-no-vendor-prefix': true,
		// 'property-unit-blacklist': {},
		// 'property-unit-whitelist': {},
		// 'property-value-blacklist': {},
		// 'property-whitelist': string|[],
		// 'root-no-standard-properties': true,
		'rule-nested-empty-line-before': ['always', {except: ['first-nested']}],
		'rule-non-nested-empty-line-before': 'always',
		'selector-class-pattern': [/(#\{\$.*?\}|[a-z0-9]+)(-#\{\$.*?\}|-[a-z0-9]+)*$/, {resolveNestedSelectors: true}], // Maybe
		'selector-combinator-space-after': 'always',
		'selector-combinator-space-before': 'always',
		// 'selector-id-pattern': string,
		'selector-list-comma-newline-after': 'always-multi-line', // Maybe
		'selector-list-comma-newline-before': 'never-multi-line',
		'selector-list-comma-space-after': 'always-single-line',
		'selector-list-comma-space-before': 'never',
		// 'selector-max-specificity': string,
		// 'selector-no-attribute': true,
		// 'selector-no-combinator': true,
		// 'selector-no-id': true,
		// 'selector-no-type': true,
		// 'selector-no-universal': true,
		// 'selector-no-vendor-prefix': true,
		'selector-pseudo-element-colon-notation': 'single',
		// 'selector-root-no-composition': true,
		'selector-type-case': 'lower',
		'string-no-newline': true,
		// 'string-quotes': 'single',
		'time-no-imperceptible': true,
		// 'unit-blacklist': string|[],
		// 'unit-whitelist': string|[],
		'value-list-comma-newline-after': 'always-multi-line',
		'value-list-comma-newline-before': 'never-multi-line',
		'value-list-comma-space-after': 'always-single-line',
		'value-list-comma-space-before': 'never',
		// 'value-no-vendor-prefix': true
	}
};